### ISSUE TITLE
Resumen de Scrum

### ISSUE THREAD

**Issue by florenciamorisse** [florenciamorisse/Proyecto_ispc_01#1]
Cuáles son las ceremonias y qué son?
Qué son los artefactos y cuáles son?
Cuáles son los roles?

**Comment by TatianaFadda** [comment]
Cuáles son las ceremonias y qué son?
**Ceremonias**: Son reuniones que tienen lugar en las iteraciones o Sprints. Entre ellas se encuentran:
●_Sprint Planning Meeting_ (reunión de planificación del sprint). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.
● _Daily Scrum Meeting_ (reunión periódica). Se produce diariamente, y tiene un máximo de 20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
● _Sprint Review Meeting_ (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner.
● _Sprint Retrospective Meeting_ (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

¿Qué son los artefactos y características son?
Artefacto en Scrum son aquellos elementos físicos que se producen como resultado de la aplicación de Scrum. 
Los tres principales artefactos o herramientas Scrum son: 
_Product Backlog_:una lista, en cualquier formato, que contiene todos los requerimientos que necesitamos implementar en el producto
_Sprint Backlog_:Se trata de una lista de elementos en los que trabajar durante la etapa de Sprint.
_Incremento_:es el resultado del Sprint, es la suma de todas las tareas, casos de uso, historias de usuario y cualquier elemento que se haya desarrollado durante el Sprint .

Cuáles son los roles?
**ROLES SCRUM:**
_Product Owner_: responsable de ese producto(miembro interno o externo). Presenta el backlog(lista priorizada de funcionalidades que debe contener un producto, o lista de tareas pendientes o  "artefacto")
_Developer Team_: equipos multidisciplinarios que pueden trabajar de manera remota.
_Scrum Master_: facilitador, nexo entre product owner y el developer team, es quien allana el camino de los equipos agil .

**Comment by TatianaFadda** [comment]
¿Cuáles son las ceremonias y qué son?
Ceremonias : Son reuniones que tienen lugar en las iteraciones o Sprints. Entre ellas se encuentran:
●_Sprint Planning Meeting_ (reunión de planificación del sprint_). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.
● _Daily_ Scrum Meeting (reunión _periódica)._ Se produce diariamente, y tiene un máximo de 20 min. de duracion Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
● _Reunión de revisión de Sprint(reunión de revisión del Sprint)._ Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner.
● _Sprint Retrospective Meeting (reunión de retrospectiva del Sprint)._ Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

¿Qué son los artefactos y características son?
**Artefactos** en Scrum son aquellos elementos físicos que se producen como resultado de la aplicación de Scrum.
Los tres principales artefactos o herramientas Scrum son:
_Product Backlog_ : es una lista, en cualquier formato, que contiene todos los requisitos que necesitamos implementar en el producto
_Sprint Backlog_ :Se trata de una lista de elementos en los que trabajarán durante la etapa de Sprint.
_Incremento_ : es el resultado del Sprint, es la suma de todas las tareas, casos de uso, historias de usuario y cualquier elemento que se haya desarrollado durante el Sprint.

**Comment by TatianaFadda** [comment]
¿Cuáles son los roles?
**ROLES SCRUM**
_Product Owner_ : responsable de ese producto (miembro interno o externo). Presenta el backlog(lista priorizada de funcionalidades que debe contener un producto, o lista de tareas pendientes o "artefacto")
_Developer Team_ : equipos multidisciplinarios que pueden trabajar de manera remota.
_Scrum Master_ : es el facilitador, nexo entre product Owner y el equipo de desarrolladores, es quien allana el camino de los equipos ágil .
