### ISSUE TITLE
Generar resumen Git

### ISSUE THREAD

**Issue by florenciamorisse** [florenciamorisse/Proyecto_ispc_01#11]
Acá vamos a compartir enlaces de interés de Python

**Comment by FirstGeneralRavioli** [comment]
Git es un sitema de control de versiones de codigo abierto, diseñado para trabajar en cualquier tipo de proyectos. 
Que nos permite conocer los cambios realizados en sw a medida que vamos desarrollandolos, nos permite coordinar el trabajo entre diferentes desarrolladores, y posee repositorios locales y remotos
Entre sus ventajas se encuentran un sistema distribuido que permite el trabajo sin conexion, su velocidad, puede crear y mezclar ramas con baja probabilidad de problemas. integridad de la informacion gracias a su modelo de almacenamiento, buen flujo de trabajo, operaciones locales, copias instantaneas, y la posibilidad de versionar los cambios como nos convenga

**Comment by Meliweb1089** [comment]
Chicos agregue una parte del resumén de GIT

**Comment by federico-madrid** [comment]
Agregue algunos de los comandos básicos de Git. Quizás como idea, pueden agregar cuales fueron los cambios positivos de git en la industria del software
