### ISSUE TITLE
Generar resumen Introducción a la base de datos

### ISSUE THREAD

**Issue by florenciamorisse** [florenciamorisse/Proyecto_ispc_01#6]

**Comment by kevinpaez5** [comment]
Introducción de las bases de datos

 Las bases de datos son un pilar muy importante para la informática y su evolución, apareciendo con el fin  de cubrir la necesidad de procesar y guardar información de forma integra y segura. Principalmente en sus comienzos guardando información de empresas relacionadas al mundo del negocio.
 Actualmente almacenan y gestionan grandes volúmenes de todo tipo de información, como también accediendo fácilmente y rápidamente a la misma y realizar diferentes acciones en ella como insertar, modificar y borrar esos datos. Esto se puede llevar a cabo por un software especifico llamado 'Sistema Gestor de BBDD' que son un conjunto de programas que permiten definir, construir y manipular una base de datos. Otras acciones que se pueden realizar en una base de datos es la recuperación de datos si se llegan a perder, o recuperarse de algún fallo en si, como también acceder de forma remota, exportar o importar datos. Algunas veces se puede relacionar a un SGBD con un sistema operativo, ya que este también es un software con conjunto de programas que trabajan íntegramente y almacenan datos que el usuario provee; o como también las bases de datos pueden trabajar aisladamente del sistema operativo y usar este como un intermediario entre el usuario, las aplicaciones y la propia base de datos, esto lo pueden ser los softwares conocidos como 'MySQL', 'Oracle', 'SQL Server', entre otras.

Todo sistema gestor de datos está formado por tres partes (o modelos), estos son:

-Modelo interno, que está relacionado íntimamente a los datos almacenados y el manejo de la estructura del almacenamiento.

-Modelo conceptual, donde definimos la estructura de la base de datos.

-Modelo externo, donde existen aplicaciones y programas que nos permiten conectarnos al modelo conceptual 

 Como estructura de un SGBD - DBSM tenemos el modelo externo, donde se hayan los paneles de control, el modelo conceptual, donde se halla la estructura de la base de datos de la aplicación o sistema desarrollado, y el modelo físico, donde se guardan los datos físicos (archivos RAW) del sistema desarrollado.
 La estructura que se monta para poder almacenar los datos esta basada en entidades, con todos sus atributos, y tiene una forma de tablas

**Comment by FirstGeneralRavioli** [comment]
Todo sistema gestor de datos está formado por tres partes (o modelos).

Modelo interno, que está relacionado intimamente a los datos amacenados y el manejo de la estructura del almacenamiento.

Modelo conceptual, donde definimos la estructura de la bae de datos.

Modelo externo, donde existen maplicaciones y programas que nos permiten conectarno al modelo conceptual 

Como extructura de un SGBD - DBSM tenemos el modelo externo, donde se hayan los paneles de control, el modelo conceptual, donde se halla la estructura de la base de datos de la aplicaion o sistema desarrollado, y el modelo fisico, donde se guardan los datos fisicos (archivos RAW) del sistema desarrollado.

La estructura que se monta para poder almacenar los datos esta basada en entidades, con todos sus atributos, y tiene una forma de tablas
